Repository prgrms-fullstack-devcourse/Runova_FE, pull requests merged in 2025-09, with the labels that each got.

#23 Chore: 웹뷰 배포를 위한 tsconfig extends 제거, dirname 미적용 및 미사용 폴더 제거
  apps/web/package-lock.json
  apps/web/package.json
  apps/web/scripts/ignore-build.sh
  apps/web/tsconfig.json
  apps/web/vercel.json
  apps/web/vite.config.ts
  web/.gitignore
  web/README.md
  web/eslint.config.js
  web/index.html
  web/package-lock.json
  web/package.json
  web/public/vite.svg
  web/src/assets/react.svg
  web/src/components/common/BaseCard.tsx
  web/src/components/common/CertItem.tsx
  web/src/components/common/ListRow.tsx
  web/src/components/common/PostCard.tsx
  web/src/components/common/RouteItem.tsx
  web/src/components/common/Section.tsx
  web/src/components/common/SectionHeader.tsx
  web/src/components/common/StatCard.tsx
  web/src/hooks/useBack.ts
  web/src/main.tsx
  web/src/pages/MyCertsPage/index.tsx
  web/src/pages/MyPage/_components/ProfileSection.tsx
  web/src/pages/MyPage/index.tsx
  web/src/pages/MyPostsPage/index.tsx
  web/src/pages/MyRoutesPage/index.tsx
  web/src/styles/emotion.d.ts
  web/src/styles/global.tsx
  web/src/types/mypage.ts
  web/src/vite-env.d.ts
  web/tsconfig.json
  web/vite.config.ts
Labels: ⚙️chore

#24 Chore: Vercel 라우팅 rewrite 적용
  apps/web/tsconfig.json
  apps/web/vercel.json
  web/src/App.tsx
  web/src/components/layout/AppLayout.tsx
  web/src/components/layout/Header.tsx
  web/src/constants/colors.ts
  web/src/pages/Community/CommunityDetail/_components/CommentList.tsx
  web/src/pages/Community/CommunityDetail/_components/PostHeader.tsx
  web/src/pages/Community/CommunityDetail/index.tsx
  web/src/pages/Community/CommunityEdit/_components/EditForm.tsx
  web/src/pages/Community/CommunityEdit/index.tsx
  web/src/pages/Community/CommunityFeed/index.tsx
  web/src/pages/Community/CommunityList/_components/Carousel.tsx
  web/src/pages/Community/CommunityList/_components/DotsIndicator.tsx
  web/src/pages/Community/CommunityList/_components/SectionCarousel.tsx
  web/src/pages/Community/CommunityList/index.tsx
  web/src/pages/Community/_components/CommunityAppLayout.tsx
  web/src/pages/Community/_components/CommunityNavigator.tsx
  web/src/pages/Community/_components/Fab.tsx
  web/src/pages/Community/_components/IconHeader.tsx
  web/src/pages/Community/_components/Postcard.tsx
  web/src/pages/Community/_components/ProfileHeader.tsx
  web/src/stores/communityStore.ts
  web/src/styles/theme.ts
  web/src/types/community.ts
Labels: ⚙️chore, 🐞bugfix

#25 Feature: React Native와 Webview 인증 토큰 브릿지 추가
  app.json
  apps/web/.gitignore
  apps/web/src/hooks/useLogNativeToken.ts
  apps/web/src/lib/nativeBridge.ts
  apps/web/src/main.tsx
  apps/web/src/stores/nativeBridgeStore.ts
  apps/web/src/types/nativeBridge.type.ts
  apps/web/src/vite-env.d.ts
  eas.json
  src/components/WebScreen.tsx
  src/hooks/useWebViewMessenger.ts
Labels: ✨feature, ⚙️chore

#26 Feature: mapbox 지도 적용
  .easignore
  .gitignore
  App.tsx
  app.config.js
  app.json
  package-lock.json
  package.json
  src/constants/location.ts
  src/hooks/useLocationTracking.ts
  src/navigation/RootNavigator.tsx
  src/pages/Home/_components/CardContainer.tsx
  src/pages/Route/_components/RouteGrid.tsx
  src/pages/Run/Run.tsx
  src/pages/Run/_components/RunMap.tsx
  src/store/routeInfo.mock.ts
  src/utils/location.ts
Labels: 🎨style, ✨feature, ⚙️chore, 🔄refactor, 🐞bugfix

#30 Feature: 맵 드로잉 기능 api 연동 및 화면 플로우 개선
  src/components/Map.tsx
  src/hooks/useImageUpload.ts
  src/hooks/useLocationManager.ts
  src/hooks/useMapCapture.ts
  src/hooks/useRouteValidation.ts
  src/lib/coursesApi.ts
  src/lib/filesApi.ts
  src/navigation/RouteStackNavigator.tsx
  src/navigation/TabNavigator.tsx
  src/pages/Draw/_components/DrawMap.tsx
  src/pages/Draw/_components/DrawUI.tsx
  src/pages/Draw/_components/Toasts.tsx
  src/pages/Draw/index.tsx
  src/pages/RouteSave/index.tsx
  src/pages/Run/_components/RunMap.tsx
  src/pages/Run/index.tsx
  src/store/draw.ts
  src/store/routeSave.ts
  src/types/api.types.ts
  src/types/courses.types.ts
  src/types/files.types.ts
  src/types/image.types.ts
  src/utils/draw.ts
  src/utils/geocoding.ts
Labels: 🎨style, ✨feature, 🐞bugfix

#32 Feature: 경로 생성 api path 형식 업데이트
  src/pages/RouteSave/index.tsx
  src/services/courses.service.ts
  src/types/courses.types.ts
  src/utils/courseFormatter.ts
Labels: 🔄refactor

#35 Feature: 경로 리스트 조회 api 연결
  src/components/Card.tsx
  src/hooks/api/useRouteApi.ts
  src/pages/Route/_components/RouteGrid.tsx
  src/pages/Route/index.tsx
  src/services/courses.service.ts
  src/store/route.ts
  src/types/auth.types.ts
  src/types/courses.types.ts
Labels: ✨feature, ⚙️chore, 🔄refactor, 🐞bugfix

#36 Feature: 런닝 트래킹 컨트롤 인터페이스 구현
  src/components/Modal.tsx
  src/hooks/useLocationTracking.ts
  src/navigation/TabNavigator.tsx
  src/pages/Run/_components/ControlContainer.tsx
  src/pages/Run/_components/RunMap.tsx
  src/pages/Run/_components/StatsContainer.tsx
  src/pages/Run/index.tsx
  src/types/run.types.ts
  src/utils/runStats.ts
Labels: ✨feature

#46 feature: 인증사진 임의 업로드 기능 구현 및 게시글에 프로필 이미지, 사용자 닉네임 연결
  apps/web/src/api/posts.ts
  apps/web/src/pages/Community/CommunityDetail/_components/PostHeader.tsx
  apps/web/src/pages/Community/CommunityDetail/index.tsx
  apps/web/src/pages/Community/CommunityEdit/_components/EditForm.tsx
  apps/web/src/pages/Community/CommunityEdit/index.tsx
  apps/web/src/pages/Community/CommunityList/index.tsx
  apps/web/src/pages/Community/_components/Postcard.tsx
  apps/web/src/types/community.ts
Labels: ✨feature, 🔄refactor

#47 Feature/UI v2
  eas.json
  src/components/Card.tsx
  src/components/Map.tsx
  src/components/Modal.tsx
  src/components/TabNavigation.tsx
  src/constants/colors.ts
  src/hooks/api/useRecordsApi.ts
  src/hooks/api/useRouteApi.ts
  src/hooks/useLocationManager.ts
  src/hooks/useLocationTracking.ts
  src/hooks/useLongPress.ts
  src/hooks/useMapCapture.ts
  src/hooks/useRunModals.ts
  src/navigation/RouteStackNavigator.tsx
  src/navigation/RunTabNavigator.tsx
  src/navigation/TabNavigator.tsx
  src/pages/Auth/index.tsx
  src/pages/Detail/index.tsx
  src/pages/Draw/_components/DrawMap.tsx
  src/pages/Draw/index.tsx
  src/pages/Home/index.tsx
  src/pages/Records/_components/RecordsList.tsx
  src/pages/Records/_components/StatsDisplay.tsx
  src/pages/Records/_components/TimeRangeSelector.tsx
  src/pages/Records/index.tsx
  src/pages/Route/_components/RouteGrid.tsx
  src/pages/Route/index.tsx
  src/pages/RouteSave/index.tsx
  src/pages/Run/_components/ControlContainer.tsx
  src/pages/Run/_components/RecommendationContainer.tsx
  src/pages/Run/_components/RunMap.tsx
  src/pages/Run/_components/StatsContainer.tsx
  src/pages/Run/index.tsx
  src/services/auth.service.ts
  src/services/courses.service.ts
  src/services/running.service.ts
  src/store/draw.ts
  src/store/run.ts
  src/types/courses.types.ts
  src/types/navigation.types.ts
  src/types/records.types.ts
  src/utils/formatters.ts
Labels: 🎨style, ✨feature, 🔄refactor, 🐞bugfix

#49 Refactor: 커뮤니티 게시글 생성 오류 수정 및 수정 / 삭제 권한 ui 적용
  apps/web/src/api/comments.ts
  apps/web/src/api/mypage.ts
  apps/web/src/api/posts.ts
  apps/web/src/pages/Community/CommunityDetail/_components/CommentList.tsx
  apps/web/src/pages/Community/CommunityDetail/_components/PostHeader.tsx
  apps/web/src/pages/Community/CommunityDetail/index.tsx
Labels: 🔄refactor

#50 fix: 글 작성 에러 수정
  apps/web/src/api/courses.ts
  apps/web/src/api/posts.ts
  apps/web/src/pages/Community/CommunityDetail/index.tsx
  apps/web/src/pages/Community/CommunityEdit/_components/EditForm.tsx
  apps/web/src/pages/Community/CommunityEdit/index.tsx
  apps/web/src/pages/Community/_components/CommunityNavigator.tsx
Labels: 🐞bugfix

#53 fix: 커뮤니티 navbar 자유게시판 추가 적용
  apps/web/src/pages/Community/CommunityFeed/index.tsx
  apps/web/src/pages/Community/_components/CommunityNavigator.tsx
  apps/web/src/stores/communityStore.ts
  apps/web/src/types/community.ts
Labels: 🐞bugfix

#54 feature: 다운로드 페이지 추가
  apps/web/index.html
  apps/web/public/favicon.png
  apps/web/public/images/community.jpg
  apps/web/public/images/navigate.jpg
  apps/web/public/images/track.jpg
  apps/web/public/vite.svg
  apps/web/src/App.tsx
  apps/web/src/hooks/useConstellation.ts
  apps/web/src/pages/Home/index.tsx
  apps/web/src/styles/global.tsx
Labels: 🎨style, ✨feature, 🐞bugfix
