Repository prgrms-fullstack-devcourse/Runova_FE, pull requests merged in 2025-08, with the labels that each got.

#8 Feature: 커뮤니티 페이지 퍼블리싱
  package-lock.json
  package.json
  src/navigation/RootNavigator.tsx
  src/pages/CommunityDetail/_components/CommentList.tsx
  src/pages/CommunityDetail/index.tsx
  src/pages/CommunityEdit/index.tsx
  src/pages/CommunityList/_components/CategoryTabs.tsx
  src/pages/CommunityList/_components/FloatingActionButton.tsx
  src/pages/CommunityList/_components/PostItem.tsx
  src/pages/CommunityList/index.tsx
  src/pages/Home/Home.tsx
  src/store/community.mock.ts
  src/styles/.gitkeep
  src/types/.gitkeep
  src/types/community.ts
  src/types/navigation.types.ts
Labels: ✨feature, ⚙️chore

#11 Feature: 홈, 경로 페이지 퍼블리싱
  README.md
  package-lock.json
  package.json
  src/assets/bear.png
  src/assets/chick.png
  src/assets/dog.png
  src/assets/gps art sample1.png
  src/assets/woman.png
  src/components/Card.tsx
  src/components/FloatingButton.tsx
  src/components/Header.tsx
  src/components/TabNavigation.tsx
  src/data/mock.ts
  src/navigation/RootNavigator.tsx
  src/navigation/TabNavigator.tsx
  src/pages/CommunityDetail/_components/CommentList.tsx
  src/pages/CommunityDetail/index.tsx
  src/pages/CommunityEdit/index.tsx
  src/pages/CommunityList/_components/CategoryTabs.tsx
  src/pages/CommunityList/_components/FloatingActionButton.tsx
  src/pages/CommunityList/_components/PostItem.tsx
  src/pages/CommunityList/index.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/_components/CardContainer.tsx
  src/pages/Home/_components/FloatingImage.tsx
  src/pages/Home/_components/FloatingImageContainer.tsx
  src/pages/Route/Route.tsx
  src/pages/Route/_components/RouteGrid.tsx
  src/pages/Run/Run.tsx
  src/pages/Settings/Settings.tsx
  src/store/community.mock.ts
  src/styles/.gitkeep
  src/types/.gitkeep
  src/types/card.types.ts
  src/types/community.ts
  src/types/home.types.ts
  src/types/navigation.types.ts
  tsconfig.json
Labels: ✨feature, ⚙️chore, 📚docs

#14 Feature: 모바일 ui 안전영역 처리 개선
  src/components/FloatingButton.tsx
  src/components/Header.tsx
  src/navigation/TabNavigator.tsx
Labels: ✨feature

#18 Feature: 로그인 기능 구현
  .env.example
  .gitignore
  App.tsx
  app.json
  eas.json
  package-lock.json
  package.json
  src/lib/api.ts
  src/navigation/RootNavigator.tsx
  src/pages/Auth/index.tsx
  src/pages/CommunityDetail/_components/CommentList.tsx
  src/pages/CommunityEdit/index.tsx
  src/pages/CommunityList/_components/CategoryTabs.tsx
  src/pages/CommunityList/_components/PostItem.tsx
  src/pages/CommunityList/index.tsx
  src/store/auth.ts
  src/store/community.mock.ts
  src/types/community.type.ts
  src/types/navigation.types.ts
  src/types/user.types.ts
Labels: ✨feature, ⚙️chore, 🔄refactor
